service: ackodrive-geodude

provider:
  name: aws
  runtime: nodejs10.x

  stage: prod
  region: ap-south-1

functions:
  geodude:
    handler: handler.getGEOData
    events:
      - http: GET /geo

plugins:
  - serverless-offline
  - serverless-plugin-scripts

custom:
  scripts:
    commands:
      datasetdownload: node download.js